### ISSUE TITLE
Objective C url signer not working

### ISSUE THREAD

**Issue by JasonPrenger** [googlemaps/url-signing#1]
Also here: https://stackoverflow.com/questions/36162763/objective-c-google-statics-maps-api-hmac-signature

I'm using the objective c version of the url-signing and its just not working for me. Every time I try I get the following error

> The Google Maps API server rejected your request. Unable to authenticate the request. Provided 'signature' is not valid for the provided API key, or the provided 'key' is not valid...

This is an example of the string I'm using to generate the signature

> /maps/api/staticmap/format=jpg&maptype=satellite&size=640x640&zoom=18&sensor=false&center=33.35853437,-111.93105310&key=[API_KEY]

With the final value being of the form

> https://maps.googleapis.com/maps/api/staticmap?format=jpg&maptype=satellite&size=640x640&zoom=18&sensor=false&center=33.35853437,-111.93105310&key=[API_KEY]&signature=[SIGNATURE]

**Comment by JasonPrenger** [comment]
Just kidding, I'm an idiot and was separating the path and query with a '/' instead of a '?'

**Comment by domesticmouse** [comment]
Glad you figured it out @ShotJP =)
