### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by pmusolino** [googlemaps/url-signing#8]
Do you have in plan a Swift implementation?

**Comment by domesticmouse** [comment]
We accept open source contributions to this repository. Failing that, I'll have a look at it at some point. Thanks!

**Comment by pmusolino** [comment]
An implementation that does not use external libraries would be really appreciated.

**Comment by pmusolino** [comment]
I've added the Swift implementation: https://github.com/googlemaps/url-signing/pull/10

**Comment by domesticmouse** [comment]
Thanks for your contribution @pmusolino, much appreciated!
